USE [Comic]
GO

EXEC	[dbo].[SPInsertHero]
		@Name = 'Aquaman',
		@Description = 'El poder más reconocido de Aquaman es la capacidad telepática para comunicarse con la vida marina, la cual puede convocar a grandes distancias.',
		@ImagePath = 'Contents\Img\Aquaman.jpg',
		@FullName = 'Orin',
		@Gender = 'M',
		@Appearance = '1941-11-1',
		@Alias = 'Dweller in the Depths, Swimmer, Waterbearer, Mental Man, Aquaboy, Water Wraith',
		@Publisher = 'DC Comics',
		@Intelligence = 81,
		@Strength = 85,
		@Speed = 79,
		@Durability = 80,
		@Power = 100,
		@Combat = 80

EXEC	[dbo].[SPInsertHero]
		@Name = 'Batman',
		@Description = 'Los rasgos principales de Batman se resumen en destreza física, habilidades deductivas y obsesión. La mayor parte de las características básicas de los cómics han variado por las diferentes interpretaciones que le han dado al personaje.',
		@ImagePath = 'Contents\Img\Batman.jpg',
		@FullName = 'Bruce Wayne',
		@Gender = 'M',
		@Appearance = '1939-5-1',
		@Alias = 'Batman, The Tomorrow Knight, The Dark Knight, The Dark Knight of Tomorrow, Batman Beyond',
		@Publisher = 'DC Comics',
		@Intelligence = 100,
		@Strength = 26,
		@Speed = 27,
		@Durability = 50,
		@Power = 47,
		@Combat = 100

EXEC	[dbo].[SPInsertHero]
		@Name = 'Daredevil',
		@Description = 'Al haber perdido la vista, los cuatro sentidos restantes de Daredevil fueron aumentados por la radiación a niveles superhumanos, en el accidente que tuvo cuando era niño. A pesar de su ceguera, puede "ver" a través de un "sexto sentido" que le sirve como un radar similar al de los murciélagos.',
		@ImagePath = 'Contents\Img\Daredevil.jpg',
		@FullName = 'Matt Murdock',
		@Gender = 'M',
		@Appearance = '1964-1-1',
		@Alias = 'Matt, Jack Batlin, Kingpin of Crime, Laurent LeVasseur, Michael \"Mike\" Murdock, Scarlet Swashbuckler, Nameless One, Kingpin of Hell"s Kitchen,The Man Without Fear, The Guardian Devil, DD, Red, Hornhead, Cooper Peyton, Captain Universe',
		@Publisher = 'Marvel Comics',
		@Intelligence = 75,
		@Strength = 13,
		@Speed = 25,
		@Durability = 35,
		@Power = 61,
		@Combat = 100

EXEC	[dbo].[SPInsertHero]
		@Name = 'Hulk',
		@Description = 'Su principal poder es su capacidad de aumentar su fuerza hasta niveles prácticamente ilimitados a la vez que aumenta su furia. Dependiendo de qué personalidad de Hulk esté al mando en ese momento (el Hulk Banner es el más débil, pero lo compensa con su inteligencia).',
		@ImagePath = 'Contents\Img\Hulk.jpg',
		@FullName = 'Bruce Banner',
		@Gender = 'M',
		@Appearance = '1962-5-1',
		@Alias = 'Annihilator, Captain Universe, Joe Fixit, Mr. Fixit, Mechano, Professor, Jade Jaws, Golly Green Giant',
		@Publisher = 'Marvel Comics',
		@Intelligence = 88,
		@Strength = 100,
		@Speed = 63,
		@Durability = 100,
		@Power = 98,
		@Combat = 85

EXEC	[dbo].[SPInsertHero]
		@Name = 'Linterna Verde',
		@Description = 'Poseedor del anillo de poder que posee la capacidad de crear manifestaciones de luz sólida mediante la utilización del pensamiento. Es alimentado por la Llama Verde (revisada por escritores posteriores como un poder místico llamado Starheart), una llama mágica contenida en dentro de un orbe (el orbe era en realidad un meteorito verde de metal que cayó a la Tierra, el cual encontró un fabricante de lámparas llamado Chang).',
		@ImagePath = 'Contents\Img\Linterna Verde.jpg',
		@FullName = 'Alan Ladd Wellington Scott',
		@Gender = 'M',
		@Appearance = '1940-7-1',
		@Alias = 'Green Lantern, White King, Sentinal',
		@Publisher = 'DC Comics',
		@Intelligence = 63,
		@Strength = 80,
		@Speed = 23,
		@Durability = 90,
		@Power = 100,
		@Combat = 32

EXEC	[dbo].[SPInsertHero]
		@Name = 'Spider-Man',
		@Description = 'Tras ser mordido por una araña radiactiva, obtuvo los siguientes poderes sobrehumanos, una gran fuerza, agilidad, poder trepar por paredes. La fuerza de Spider-Man le permite levantar 10 toneladas o más. Gracias a esta gran fuerza Spider-Man puede realizar saltos íncreibles. Un \"sentido arácnido\", que le permite saber si un peligro se cierne sobre él, antes de que suceda. En ocasiones este puede llevar a Spider-Man al origen del peligro.',
		@ImagePath = 'Contents\Img\Spider-Man.jpg',
		@FullName = 'Peter Parker',
		@Gender = 'M',
		@Appearance = '1962-8-1',
		@Alias = 'Spiderman, Bag-Man, Black Marvel, Captain Universe, Dusk, Green Hood, Hornet, Mad Dog 336, Peter Palmer, Prodigy, Ricochet, Scarlet Spider, Spider-Boy, Spider-Hulk, Spider-Morphosis',
		@Publisher = 'Marvel Comics',
		@Intelligence = 90,
		@Strength = 55,
		@Speed = 67,
		@Durability = 75,
		@Power = 74,
		@Combat = 85

EXEC	[dbo].[SPInsertHero]
		@Name = 'Wolverine',
		@Description = 'En el universo ficticio de Marvel, Wolverine posee poderes regenerativos que pueden curar cualquier herida, por mortal que ésta sea, además ese mismo poder hace que sea inmune a cualquier enfermedad existente en la Tierra y algunas extraterrestres . Posee también una fuerza sobrehumana, que si bien no se compara con la de otros superhéroes como Hulk, sí sobrepasa la de cualquier humano.',
		@ImagePath = 'Contents\Img\Wolverine.jpg',
		@FullName = 'Logan',
		@Gender = 'M',
		@Appearance = '1974-11-1',
		@Alias = 'Weapon X, Weapon Ten, Death, Mutate 9601, Jim Logan, Emilio Garra, Weapon Chi, Experiment X, Agent Ten, Peter Richards, Mai kethLogan, Mr. Patch',
		@Publisher = 'Marvel Comics',
		@Intelligence = 63,
		@Strength = 32,
		@Speed = 50,
		@Durability = 100,
		@Power = 89,
		@Combat = 100

EXEC	[dbo].[SPInsertHero]
		@Name = 'Ant-Man',
		@Description = 'Armado con un supertraje con la asombrosa capacidad de reducir su escala pero aumentar su fuerza, Scott Lang era un ladrón que se convirtió en Ant-Man después de robar el traje de Ant-Man para salvar a su hija Cassandra "Cassie" Lang de una afección cardíaca.',
		@ImagePath = 'Contents\Img\Ant-Man.jpg',
		@FullName = 'Scott Lang',
		@Gender = 'M',
		@Appearance = '1979-3-1',
		@Alias = 'Myrmidon, Scott Edward Harris Lang, Ant-Man, Goliath, Wasp',
		@Publisher = 'Marvel Comics',
		@Intelligence = 75,
		@Strength = 18,
		@Speed = 17,
		@Durability = 40,
		@Power = 53,
		@Combat = 30

EXEC	[dbo].[SPInsertHero]
		@Name = 'Black Cat',
		@Description = 'Ella es una ladrona de gatos profesional que a menudo se encuentra con Spider-Man, pero a veces actúa como aliada en ciertas situaciones. A pesar de su lado malvado, Black Cat ha trabajado con otros superhéroes para detener amenazas y supervillanos.',
		@ImagePath = 'Contents\Img\Black Cat.jpg',
		@FullName = 'Felicia Hardy',
		@Gender = 'F',
		@Appearance = '1979-7-1',
		@Alias = 'Felicity Harmon',
		@Publisher = 'Marvel Comics',
		@Intelligence = 75,
		@Strength = 16,
		@Speed = 33,
		@Durability = 10,
		@Power = 23,
		@Combat = 70

EXEC	[dbo].[SPInsertHero]
		@Name = 'Black Panther',
		@Description = 'Además de poseer habilidades mejoradas logradas a través de los antiguos rituales de Wakandan de beber la esencia de la hierba en forma de corazón, también se basa en su dominio de la ciencia, experiencia en las tradiciones de su nación, entrenamiento físico riguroso, habilidades de combate cuerpo a cuerpo, y acceso a la riqueza y tecnología avanzada de Wakandan para combatir a sus enemigos.',
		@ImagePath = 'Contents\Img\Black Panther.jpg',
		@FullName = 'T"Challa',
		@Gender = 'M',
		@Appearance = '1966-7-1',
		@Alias = 'Mr. Okonkwo, The Man Without Fear, Luke Charles, Black Leopard, the Client, Coal Tiger',
		@Publisher = 'Marvel Comics',
		@Intelligence = 88,
		@Strength = 16,
		@Speed = 30,
		@Durability = 60,
		@Power = 41,
		@Combat = 100

EXEC	[dbo].[SPInsertHero]
		@Name = 'Black Widow',
		@Description = 'Una agente rusa entrenada como espía, artista marcial y francotiradora, y equipada con un arsenal de armas de alta tecnología, que incluye un par de armas energéticas montadas en la muñeca y apodada "Piquete de la Viuda".',
		@ImagePath = 'Contents\Img\Black Widow.jpg',
		@FullName = 'Natasha Romanoff',
		@Gender = 'F',
		@Appearance = '1964-4-1',
		@Alias = 'Yelena Belova, Natasha Romanoff, Natasha, Tasha, Madame Natasha, Nancy Rushman, Laura Matthers, Nadine Roman, "Oktober", Black Pearl, Ebon Flame',
		@Publisher = 'Marvel Comics',
		@Intelligence = 75,
		@Strength = 13,
		@Speed = 33,
		@Durability = 30,
		@Power = 36,
		@Combat = 100

EXEC	[dbo].[SPInsertHero]
		@Name = 'Blade',
		@Description = 'Blade posee todas las fortalezas de un vampiro sin sus debilidades. Tiene fuerza, resistencia y sentidos sobrehumanos, así como un factor de curación acelerado, pero es impermeable a la luz del sol y las mordeduras de vampiros. Además de sus habilidades sobrenaturales, también es un luchador increíblemente hábil.',
		@ImagePath = 'Contents\Img\Blade.jpg',
		@FullName = 'Eric Brooks',
		@Gender = 'M',
		@Appearance = '1973-7-1',
		@Alias = 'Switchblade, Frank Blade, Daywalker',
		@Publisher = 'Marvel Comics',
		@Intelligence = 63,
		@Strength = 28,
		@Speed = 38,
		@Durability = 50,
		@Power = 40,
		@Combat = 90

EXEC	[dbo].[SPInsertHero]
		@Name = 'Captain America',
		@Description = 'Receptor del suero del Supersoldado, el héroe de la Segunda Guerra Mundial Steve Rogers lucha por los ideales estadounidenses como uno de los héroes más poderosos del mundo.',
		@ImagePath = 'Contents\Img\Captain America.jpg',
		@FullName = 'Steve Rogers',
		@Gender = 'M',
		@Appearance = '1941-3-1',
		@Alias = 'Nomad, The Captain',
		@Publisher = 'Marvel Comics',
		@Intelligence = 69,
		@Strength = 19,
		@Speed = 38,
		@Durability = 55,
		@Power = 60,
		@Combat = 100

EXEC	[dbo].[SPInsertHero]
		@Name = 'Captain Marvel',
		@Description = 'La ex piloto de la Fuerza Aérea y agente de inteligencia Carol Danvers persiguió su sueño de explorar el espacio como empleada de la NASA, pero su vida cambió para siempre cuando se transformó accidentalmente en un híbrido humano-kree con poderes extraordinarios.',
		@ImagePath = 'Contents\Img\Captain Marvel.jpg',
		@FullName = 'Carol Danvers',
		@Gender = 'F',
		@Appearance = '1968-3-1',
		@Alias = 'Ace, Binary, Lady Marvel, Warbird',
		@Publisher = 'Marvel Comics',
		@Intelligence = 84,
		@Strength = 88,
		@Speed = 71,
		@Durability = 95,
		@Power = 100,
		@Combat = 90

EXEC	[dbo].[SPInsertHero]
		@Name = 'Catwoman',
		@Description = 'Catwoman es una criminal con temática felina de Gotham City y uno de los enemigos más conocidos de Batman . Selina Kyle a menudo se presenta como una ladrona y un ladrón de gatos con lealtades divididas. Sus actividades delictivas a menudo se ven atenuadas por un altruismo reacio, lo que la convierte en una villana inconstante y una aliada ocasional de Batman.',
		@ImagePath = 'Contents\Img\Catwoman.jpg',
		@FullName = 'Selina Kyle',
		@Gender = 'F',
		@Appearance = '1940-3-1',
		@Alias = 'The Cat, Irena Dubrovna, Elva Barr, Sadie Kelowski, Madame Moderne, Marguerite Tone',
		@Publisher = 'DC Comics',
		@Intelligence = 69,
		@Strength = 11,
		@Speed = 33,
		@Durability = 28,
		@Power = 27,
		@Combat = 85

EXEC	[dbo].[SPInsertHero]
		@Name = 'Cyclops',
		@Description = 'Cyclops es miembro de una subespecie de humanos conocida comomutantes, que nacen con habilidades sobrehumanas . Cyclops emite poderosos rayos de energía de sus ojos y solo puede controlar los rayos con la ayuda de gafas especiales que debe usar en todo momento.',
		@ImagePath = 'Contents\Img\Cyclops.jpg',
		@FullName = 'Scott Summers',
		@Gender = 'M',
		@Appearance = '1963-9-1',
		@Alias = 'Scotty, Cyke, Slim, Fearless Leader, One-Eye, Erik the Red, Slym Dayspring, Mutate 007, Apocalypse',
		@Publisher = 'Marvel Comics',
		@Intelligence = 75,
		@Strength = 10,
		@Speed = 23,
		@Durability = 42,
		@Power = 76,
		@Combat = 80

EXEC	[dbo].[SPInsertHero]
		@Name = 'Doctor Strange',
		@Description = 'Doctor Strange actúa como Hechicero Supremo, el principal protector de la Tierra contra las amenazas mágicas y místicas .',
		@ImagePath = 'Contents\Img\Doctor Strange.jpg',
		@FullName = 'Stephen Strange',
		@Gender = 'M',
		@Appearance = '1963-7-1',
		@Alias = 'Sorcerer Supreme, Master of the Mystic Arts, Stephen Sanders, Captain Universe, Vincent Stevens',
		@Publisher = 'Marvel Comics',
		@Intelligence = 100,
		@Strength = 10,
		@Speed = 12,
		@Durability = 84,
		@Power = 100,
		@Combat = 60

EXEC	[dbo].[SPInsertHero]
		@Name = 'Firestorm',
		@Description = 'Firestorm tiene la capacidad de reorganizar las estructuras moleculares o de partículas de cualquier sustancia en casi cualquier otra cosa, creando diferentes estructuras atómicas de igual masa . Puede transmutar la composición básica de un objeto (p. ej., transmutar el plomo en oro) y también puede cambiar su forma a voluntad.',
		@ImagePath = 'Contents\Img\Firestorm.jpg',
		@FullName = 'Jason Rusch',
		@Gender = 'M',
		@Appearance = '1978-3-1',
		@Alias = 'The Nuclear Man',
		@Publisher = 'DC Comics',
		@Intelligence = 50,
		@Strength = 53,
		@Speed = 58,
		@Durability = 56,
		@Power = 100,
		@Combat = 42

EXEC	[dbo].[SPInsertHero]
		@Name = 'Flash',
		@Description = 'Es un científico de la policía que ganó supervelocidad cuando se bañó con productos químicos después de que un rayo cayera sobre un estante.',
		@ImagePath = 'Contents\Img\Flash.jpg',
		@FullName = 'Barry Allen',
		@Gender = 'M',
		@Appearance = '1956-10-1',
		@Alias = 'The Scarlet Speedster, the Fastest Man Alive, the Monarch of Motion, the Sultan of Speed',
		@Publisher = 'DC Comics',
		@Intelligence = 88,
		@Strength = 48,
		@Speed = 100,
		@Durability = 60,
		@Power = 100,
		@Combat = 60

EXEC	[dbo].[SPInsertHero]
		@Name = 'Gambit',
		@Description = 'Gambito pertenece a una subespecie de humanos llamada mutantes, que nacen con habilidades sobrehumanas . Gambit tiene la capacidad de crear, controlar y manipular mentalmente energía cinética pura a su gusto. También tiene un increíble conocimiento y habilidad en el lanzamiento de cartas, el combate cuerpo a cuerpo y el uso de un bastón bō.',
		@ImagePath = 'Contents\Img\Gambit.jpg',
		@FullName = 'Remy Etienne LeBeau',
		@Gender = 'M',
		@Appearance = '1990-7-1',
		@Alias = 'Death, Le Diable Blanc, formerly Robert Lord, Cajun',
		@Publisher = 'Marvel Comics',
		@Intelligence = 63,
		@Strength = 10,
		@Speed = 23,
		@Durability = 28,
		@Power = 55,
		@Combat = 84

EXEC	[dbo].[SPInsertHero]
		@Name = 'Green Arrow',
		@Description = 'Se muestra vestido como el personaje de Robin Hood, es un arquero que usa sus habilidades para luchar contra el crimen en sus ciudades natales de Star City y Seattle.',
		@ImagePath = 'Contents\Img\Green Arrow.jpg',
		@FullName = 'Oliver Queen',
		@Gender = 'M',
		@Appearance = '1941-11-1',
		@Alias = 'The Emerald Archer, Battling Bowman',
		@Publisher = 'DC Comics',
		@Intelligence = 81,
		@Strength = 12,
		@Speed = 35,
		@Durability = 28,
		@Power = 39,
		@Combat = 90

EXEC	[dbo].[SPInsertHero]
		@Name = 'Hawkeye',
		@Description = 'Un maestro tirador, increíble arquero, experto tirador y luchador, agente especial.',
		@ImagePath = 'Contents\Img\Hawkeye.jpg',
		@FullName = 'Clint Barton',
		@Gender = 'M',
		@Appearance = '1964-9-1',
		@Alias = 'Ronin, Goliath, Golden Archer, the Marksman, Father Time, Longbow',
		@Publisher = 'Marvel Comics',
		@Intelligence = 56,
		@Strength = 12,
		@Speed = 21,
		@Durability = 10,
		@Power = 29,
		@Combat = 80

EXEC	[dbo].[SPInsertHero]
		@Name = 'Iceman',
		@Description = 'Hombre de hielo es un mutante nacido con habilidades sobrehumanas . Tiene la capacidad de manipular el hielo y el frío congelando el vapor de agua a su alrededor. Esto le permite congelar objetos, así como cubrir su cuerpo con hielo.',
		@ImagePath = 'Contents\Img\Iceman.jpg',
		@FullName = 'Bobby Drake',
		@Gender = 'M',
		@Appearance = '1963-9-1',
		@Alias = 'Bobby Drake, Mister Friese, Drake Roberts, Rampage, Frozen One, Iceface',
		@Publisher = 'Marvel Comics',
		@Intelligence = 63,
		@Strength = 32,
		@Speed = 53,
		@Durability = 100,
		@Power = 100,
		@Combat = 64

EXEC	[dbo].[SPInsertHero]
		@Name = 'Iron Man',
		@Description = 'Usa una armadura modular de Iron Man impulsada por un reactor de arco, que le otorga una fuerza y ​​durabilidad sobrehumanas, la capacidad de volar y proyectar explosiones de Repulsor.',
		@ImagePath = 'Contents\Img\Iron Man.jpg',
		@FullName = 'Tony Stark',
		@Gender = 'M',
		@Appearance = '1963-3-1',
		@Alias = 'Iron Knight, Hogan Potts, Spare Parts Man, Cobalt Man II, Crimson Dynamo, Ironman',
		@Publisher = 'Marvel Comics',
		@Intelligence = 100,
		@Strength = 85,
		@Speed = 58,
		@Durability = 85,
		@Power = 100,
		@Combat = 64

EXEC	[dbo].[SPInsertHero]
		@Name = 'Jessica Jones',
		@Description = 'Es una detective privada que bebe mucho, tiene mucha fuerza y ​​tiene un pasado oscuro.',
		@ImagePath = 'Contents\Img\Jessica Jones.jpg',
		@FullName = 'Jessica Campbell Jones Cage',
		@Gender = 'F',
		@Appearance = '1963-9-1',
		@Alias = 'Knightress, Madeline, Jewel, Power Woman',
		@Publisher = 'Marvel Comics',
		@Intelligence = 56,
		@Strength = 44,
		@Speed = 50,
		@Durability = 70,
		@Power = 18,
		@Combat = 55

EXEC	[dbo].[SPInsertHero]
		@Name = 'Luke Cage',
		@Description = 'Obtuvo los poderes de fuerza sobrehumana y piel irrompible después de ser sometido voluntariamente a un procedimiento experimental.',
		@ImagePath = 'Contents\Img\Luke Cage.jpg',
		@FullName = 'Luke Cage',
		@Gender = 'M',
		@Appearance = '1972-6-1',
		@Alias = 'Carl Lucas, Power Man, Mark Lucas, Hero for Hire, Ace of Spades',
		@Publisher = 'Marvel Comics',
		@Intelligence = 50,
		@Strength = 63,
		@Speed = 29,
		@Durability = 95,
		@Power = 44,
		@Combat = 70

EXEC	[dbo].[SPInsertHero]
		@Name = 'Superman',
		@Description = 'Usando su vuelo, fuerza mejorada, visión de calor y varios otros poderes, protege el planeta y el universo de amenazas poderosas.',
		@ImagePath = 'Contents\Img\Superman.jpg',
		@FullName = 'Clark Kent',
		@Gender = 'M',
		@Appearance = '1938-6-1',
		@Alias = 'Clark Joseph Kent, The Man of Steel, the Man of Tomorrow, the Last Son of Krypton, Big Blue, the Metropolis Marvel, the Action Ace',
		@Publisher = 'DC Comics',
		@Intelligence = 94,
		@Strength = 100,
		@Speed = 100,
		@Durability = 100,
		@Power = 100,
		@Combat = 85

EXEC	[dbo].[SPInsertHero]
		@Name = 'Thor',
		@Description = 'El hijo de Odín usa sus habilidades como Dios del Trueno para proteger a Asgard y al planeta Tierra.',
		@ImagePath = 'Contents\Img\Thor.jpg',
		@FullName = 'Thor Odinson',
		@Gender = 'M',
		@Appearance = '1962-8-1',
		@Alias = 'Donald Blake, Sigurd Jarlson, Jake Olsen, Donar the Mighty',
		@Publisher = 'Marvel Comics',
		@Intelligence = 69,
		@Strength = 100,
		@Speed = 83,
		@Durability = 100,
		@Power = 100,
		@Combat = 100

GO
